### PR TITLE
chore: Code quality improvements

### PR DESCRIPTION
**Pull request by jirimoravcik**
I used https://pypi.org/project/flake8_simplify/ to get some insights and improved the code a bit

### CODE REVIEW

**Review by vdusek — APPROVED** [review]
LGTM

**Review by fnesveda — APPROVED** [review]
Cool!

**Review by vdusek — CHANGES_REQUESTED** [review]
What about adding the `flake8_simplify` package to the [dev dependencies](https://github.com/apify/apify-sdk-python/blob/master/pyproject.toml#L40)?

**Comment by jirimoravcik** [comment]
> What about adding the `flake8_simplify` package to the [dev dependencies](https://github.com/apify/apify-sdk-python/blob/master/pyproject.toml#L40)?

Yeah, I though about it.  It reports some stuff that I didn't want to change :D (specifically, using context managers for files - we have code that does `open(..).close()` which is shorter than using a context manager. But I think it's fine

**Comment by jirimoravcik** [comment]
Added `flake8-simplify` as dev dependency. Will also do for other 2 repos along with code simplification

**Comment by jirimoravcik** [comment]
> > Yeah, I though about it. It reports some stuff that I didn't want to change :D (specifically, using context managers for files - we have code that does open(..).close() which is shorter than using a context manager.
> 
> I'd use `#noqa` for such cases, up to you, both variants LGTM.

I just did the suggested change, it's better than noqa or adding the rule to flake ignores

**Pull request merged**
