### PR TITLE
ci: Automate the release process

### LINKED ISSUE #241: Automatically generate changelog from the commit messages
Same as we do in Crawlee, see https://github.com/apify/crawlee-python/issues/18.

### PR DESCRIPTION
**Pull request by janbuchar**
- closes #241

### CODE REVIEW

**Review by vdusek — CHANGES_REQUESTED** [review]
Update `.pre-commit-config.yaml` and `Makefile` please :slightly_smiling_face: .

**Review by vdusek — COMMENTED** [review]
We're removing `run_release.yaml` in the client, but leaving it in here. Is that correct?

**Review by vdusek — CHANGES_REQUESTED** [review]
All our pipeline files so far follow a verb-based naming style (`build_and_deploy_docs.yaml`, `check_pr_title.yaml`, `run_code_checks.yaml`, `update_new_issue.yaml`). The release pipelines, however, are named `release` and `pre_release`. While I'm not insisting we have to use verb-style naming—I'm not sure what the best convention is—but please keep it consistent.

**Comment by B4nan** [comment]
but `release` is also verb, right? :]

**Comment by janbuchar** [comment]
> All our pipeline files so far follow a verb-based naming style (`build_and_deploy_docs.yaml`, `check_pr_title.yaml`, `run_code_checks.yaml`, `update_new_issue.yaml`). The release pipelines, however, are named `release` and `pre_release`. While I'm not insisting we have to use verb-style naming—I'm not sure what the best convention is—but please keep it consistent.

> but release is also verb, right? :]

https://github.com/apify/apify-client-python/pull/278#issuecomment-2444852367

**Comment by janbuchar** [comment]
> We're removing `run_release.yaml` in the client, but leaving it in here. Is that correct?

It isn't! Thank you!

**Review by vdusek — APPROVED** [review]
Great job! Thanks

**Pull request merged**
